version: "3.9"
services:
  web:
    build: web
    ports:
      - "80:80"
    depends_on:
      - db
    hostname:
      website

  db:
    build: chirp-mysql
    restart: always
    ports:
      - "3306:3306"
    hostname:
      database

